Repository KPT-Final-Team9/front, pull requests merged in 2024-06, with the labels that each got.

#96 Feat/room categoryrating/#54
  src/app/(after-login)/room/@CategoryRating/page.tsx
  src/asset/Icons/index.tsx
  src/components/charts/bar-chart/ScoreTrendChart.tsx
Labels: ✨ 기능구현

#97 fix: 평가항목별 점수 리펙터링및 아이콘변경
  src/app/(after-login)/room/@CategoryRating/page.tsx
  src/asset/Icons/ic-business-chart.svg
  src/asset/Icons/index.tsx
Labels: ♻️ 리팩토링

#89 feat: DatePicker 구현
  package-lock.json
  package.json
  src/app/(after-login)/rating-detail/_component/RatingDetailDateRangePicker.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailFilter.tsx
  src/app/(after-login)/rating-detail/_store/ratingDetailStore.ts
  src/components/common/Monocles/date-input/DateInput.stories.tsx
  src/components/common/Monocles/date-input/DateInput.tsx
  src/components/common/Monocles/date-picker/DatePicker.stories.tsx
  src/components/common/Monocles/date-picker/DatePicker.tsx
  src/components/common/Monocles/popover-trigger/Popover.stories.tsx
  src/components/common/Monocles/popover-trigger/PopoverTrigger.tsx
  src/components/ui/calendar.tsx
  src/lib/utils.ts
  src/utils/index.ts
Labels: ✨ 기능구현

#99 feat: 입주 평가하기 - 평가 항목별 상세 퍼블리싱
  package-lock.json
  package.json
  src/app/(after-login)/user-survey/[...surveyStep]/page.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyDetail.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyMain.tsx
  src/app/(after-login)/user-survey/_components/SurveyHeader.tsx
  src/app/(after-login)/user-survey/_components/SurveyHeaderBackButton.tsx
  src/app/(after-login)/user-survey/_components/Test.tsx
  src/app/(after-login)/user-survey/default.tsx
  src/app/(after-login)/user-survey/page.tsx
  src/app/(after-login)/user-survey/scores/page.tsx
  src/asset/Icons/exclamation-mark.svg
  src/asset/Icons/index.tsx
  src/asset/Icons/survey_complaint.svg
  src/asset/Icons/survey_facility.svg
  src/asset/Icons/survey_manage.svg
  src/components/common/Atoms/score-slider/SliderWithTooltip.tsx
  src/components/common/Monocles/text-fields/SurveyTextField.tsx
  src/components/ui/tooltip.tsx
  src/constants/index.ts
Labels: ✨ 기능구현, 🎨 스타일

#100 feat: 입주 평가하기 - 평가 완료 화면 퍼블리싱
  src/app/(after-login)/user-survey/_components/RoomSurveyDetail.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyFinish.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyMain.tsx
  src/app/(after-login)/user-survey/_components/SurveyHeader.tsx
  src/app/(after-login)/user-survey/_components/SurveyHeaderBackButton.tsx
  src/app/(after-login)/user-survey/_components/Test.tsx
  src/app/(after-login)/user-survey/page.tsx
  src/app/(after-login)/user-survey/scores/page.tsx
  src/asset/Icons/index.tsx
  src/asset/Icons/survey_finish.svg
  src/asset/images/star1.png
  src/asset/images/star2.png
  src/constants/index.ts
  tailwind.config.ts
Labels: 🎨 스타일

#101 Test/deploy
  .dockerignore
  .github/workflows/dockerCD.yml
  .github/workflows/dockerCI.yml
  appspec.yml
  deploy.sh
  dockerfile
  next.config.mjs
  src/app/(after-login)/dashboard/@RatingTrends/_components/Modal.tsx
  src/app/page.tsx
Labels: 🚀 배포, 🏗️ 환경설정

#112 feat: Mobile GNB 퍼블리싱
  src/app/(after-login)/layout.tsx
  src/asset/Icons/ic-tooltip.svg
  src/asset/Icons/index.tsx
  src/asset/Icons/nav_account.svg
  src/asset/Icons/nav_dashboard.svg
  src/asset/Icons/nav_rating_detail.svg
  src/asset/Icons/nav_room.svg
  src/components/charts/GradientChart.tsx
  src/components/common/Organisms/navigation/DesktopGNB.tsx
  src/components/common/Organisms/navigation/MobileGNB.tsx
  tailwind.config.ts
Labels: 🎨 스타일

#113 fix: 입주자 평가하기 페이지 form score 숫자값으로 전달안되는 이슈 해결 및 검증
  src/app/(after-login)/user-survey/_components/RoomSurveyDetail.tsx
  src/asset/Icons/danger_triangle.svg
  src/asset/Icons/index.tsx
  src/components/common/Atoms/toast/UserSurveyToast.tsx
Labels: 🐛 버그

#115 feat: 입주자 평가하기 페이지 - 특정 일자에 뜨는 안내 모달 추가
  src/app/(after-login)/user-survey/_components/RoomSurveyLastModal.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyMain.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyMidModal.tsx
  src/app/(after-login)/user-survey/_store/index.ts
  src/app/(after-login)/user-survey/_store/userSurveyStore.ts
  src/app/(after-login)/user-survey/page.tsx
  src/asset/images/pushing_hand.png
  src/asset/images/writing_hand.png
  src/components/modals/SurveyReminderModal.tsx
  src/utils/index.ts
Labels: ✨ 기능구현, 🎨 스타일

#95 feat: 평가 상세 내용 페이지 잔여 작업
  package-lock.json
  package.json
  src/app/(after-login)/rating-detail/_component/BookmarkButtons.tsx
  src/app/(after-login)/rating-detail/_component/RatingDeatilSearchInput.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailDataTable.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailDateRangePicker.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailDialog.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailFilter.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailPagination.tsx
  src/app/(after-login)/rating-detail/_component/dummyData.ts
  src/app/(after-login)/rating-detail/_store/ratingDetailStore.ts
  src/app/(after-login)/rating-detail/page.tsx
  src/asset/Icons/icon-menu-dots.svg
  src/asset/Icons/index.tsx
  src/components/common/Atoms/seletbox/Selectbox.tsx
  src/components/common/Monocles/date-input/DateInput.stories.tsx
  src/components/common/Monocles/date-input/DateInput.tsx
  src/components/common/Monocles/date-picker/DatePicker.stories.tsx
  src/components/common/Monocles/date-picker/DatePicker.tsx
  src/components/ui/dialog.tsx
  src/components/ui/pagination.tsx
  src/components/ui/table.tsx
  src/types/common/selectbox.ts
  src/utils/index.ts
Labels: ✨ 기능구현

#117 fix: 상세 평가 내용 이후 발생한 빌드 버그 수정
  src/app/(after-login)/rating-detail/_component/RatingDetailPagination.tsx
  src/components/common/Atoms/seletbox/Selectbox.tsx
  src/components/common/Organisms/navigation/DesktopGNB.tsx
  src/types/common/selectbox.ts
Labels: 🐛 버그

#120 feat: 계약 정보 수정하기 구현
  src/app/(after-login)/room/@Overview/_component/ContractEditConfirmDialog.tsx
  src/app/(after-login)/room/@Overview/_component/ContractEditDialog.tsx
  src/app/(after-login)/room/@Overview/_component/ContractEditDialogContent.tsx
  src/app/(after-login)/room/@Overview/_component/ContractInfoServerComp.tsx
  src/app/(after-login)/room/@Overview/_component/ContractVacantConfirmDialog.tsx
  src/asset/Icons/icon_edit.svg
  src/asset/Icons/index.tsx
  src/asset/images/yellow-check-mark.png
  src/asset/images/yellow-important-box.png
  src/components/common/Monocles/date-input/DateInput.stories.tsx
  src/components/common/Monocles/date-input/DateInputAtom.tsx
  src/components/ui/dialog.tsx
  src/utils/index.ts
Labels: ✨ 기능구현

#121 feat: 툴팁 추가
  src/app/(after-login)/dashboard/@MainRoomCompare/page.tsx
  src/app/(after-login)/dashboard/_components/IndexTooltip.tsx
  src/app/(after-login)/room/@CategoryRating/page.tsx
  src/app/(after-login)/room/@Overview/_component/ContractEditDialogContent.tsx
  src/app/(after-login)/room/@Overview/_component/RatingCompareComp.tsx
  src/app/(after-login)/room/_component/RoomTooltip.tsx
  src/asset/Icons/exclamation-mark.svg
  src/components/common/Atoms/tooltip/BlackTooltip.stories.tsx
  src/components/common/Atoms/tooltip/BlackTooltipContent.tsx
  src/components/icon/index.tsx
  src/middleware.tsx
Labels: ✨ 기능구현

#123 feat: 입주자 평가하기 페이지 - api 연동
  src/app/(after-login)/user-survey/_components/RoomSurveyDetail.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyMain.tsx
  src/app/(after-login)/user-survey/page.tsx
  src/app/(after-login)/user-survey/scores/page.tsx
  src/components/ui/alert-dialog.tsx
  src/constants/index.ts
  src/middleware.tsx
  src/serverActions/survey.ts
  src/utils/index.ts
Labels: ✨ 기능구현

#124 feat:대시보드 api연동
  src/app/(after-login)/dashboard/@MainRoomCompare/_components/RowBarComp.tsx
  src/app/(after-login)/dashboard/@MainRoomCompare/loading.tsx
  src/app/(after-login)/dashboard/@MainRoomCompare/page.tsx
  src/app/(after-login)/dashboard/@MainRoomSchedule/loading.tsx
  src/app/(after-login)/dashboard/@MainRoomSchedule/page.tsx
  src/app/(after-login)/dashboard/@Overview/_components/BarChart.tsx
  src/app/(after-login)/dashboard/@Overview/_components/HalfCircleProgress.tsx
  src/app/(after-login)/dashboard/@Overview/_components/SelectComp.tsx
  src/app/(after-login)/dashboard/@Overview/_store/index.tsx
  src/app/(after-login)/dashboard/@Overview/page.tsx
  src/app/(after-login)/dashboard/@RatingTrends/_components/LineChartComp.tsx
  src/app/(after-login)/dashboard/@RatingTrends/_components/Modal.tsx
  src/app/(after-login)/dashboard/@RatingTrends/_store/index.tsx
  src/app/(after-login)/dashboard/@RatingTrends/page.tsx
  src/app/(after-login)/dashboard/_components/DocumentStorageBox.tsx
  src/app/(after-login)/dashboard/layout.tsx
  src/app/(before-login)/(auth)/login/page.tsx
  src/auth.ts
  src/components/charts/CustomLables.tsx
  src/components/charts/GradientChart.stories.tsx
  src/components/charts/GradientChart.tsx
  src/components/charts/GradientTooltip.tsx
  src/components/charts/bar-chart/MultiBarChart.tsx
  src/components/charts/bar-chart/SingleCategoryHorizontalBarChart.tsx
  src/components/common/Atoms/badge/RoomBadge.tsx
  src/components/common/Atoms/badge/ScoreBadge.stories.tsx
  src/components/common/Atoms/badge/ScoreBadge.tsx
  src/components/common/Atoms/buttons/IconButtons.tsx
  src/components/common/Atoms/seletbox/Selectbox.tsx
  src/components/common/Monocles/progress-bar/CircleProgressRating.tsx
  src/components/common/Monocles/progress-bar/ContractProgress.tsx
  src/components/common/Monocles/progress-bar/HalfCircularProgressRating.tsx
  src/components/common/Organisms/navigation/DesktopGNB.tsx
  src/constants/index.ts
  src/hooks/index.tsx
  src/services/api.tsx
  src/services/intercepter.ts
  src/types/common/pageTypes.ts
  src/utils/index.ts
  tailwind.config.ts
Labels: ✨ 기능구현, ♻️ 리팩토링

#122 fix: 호실별 페이지 레이아웃 깨지는 버그 수정
  src/app/(after-login)/room/@Overview/_component/ContractInfoServerComp.tsx
  src/app/(after-login)/room/@RatingManagement/_component/RatingManagementServerComp.tsx
Labels: 🐛 버그

#127 Docs: README 1차 업데이트
  README.md
Labels: 📝 문서
