Repository KPT-Final-Team9/front, pull requests merged in 2024-05, with the labels that each got.

#14 fix: 스토리북 충돌 해결
  package-lock.json
Labels: 🐛 버그

#18 Feat: 버튼 추가
  package-lock.json
  package.json
  src/app/globals.scss
  src/asset/Icons/ic-next.svg
  src/asset/Icons/icon_alarm.svg
  src/asset/Icons/index.tsx
  src/components/common/Atoms/buttons/IconButton.stories.tsx
  src/components/common/Atoms/buttons/IconButton.tsx
  src/components/common/Atoms/buttons/IconButtons.tsx
  src/components/common/Atoms/buttons/NextIconButton.stories.tsx
  src/components/common/Atoms/buttons/NextIconButton.tsx
  src/components/common/Atoms/buttons/NotiBellButton.stories.tsx
  src/components/common/Atoms/buttons/NotiBellButton.tsx
  src/components/common/Monocles/text-fields/CommonTextField.tsx
  src/components/icon/index.tsx
  src/components/ui/button.stories.tsx
  src/components/ui/button.tsx
Labels: ✨ 기능구현, ♻️ 리팩토링, 🎨 스타일

#19 doc: notibell icon doc 추가
  src/components/common/Atoms/buttons/NotiBellButton.tsx
Labels: 📝 문서

#20 refactor: icon 옵셔널로 prop 받을 수 있게 수정
  src/asset/Icons/icon_alarm.svg
  src/components/common/Atoms/buttons/NotiBellButton.tsx
  src/components/icon/index.tsx
Labels: ♻️ 리팩토링

#21 Feat: 공통 배찌, 라벨
  src/app/page.tsx
  src/asset/Icons/ic-speechbubble.svg
  src/asset/Icons/icon_star.svg
  src/asset/Icons/index.tsx
  src/components/charts/CustomLables.tsx
  src/components/charts/MainVerticalBarChart.tsx
  src/components/charts/MainVerticalBartChart.stories.tsx
  src/components/charts/bar-chart/SingleCategoryHorizontalBarChart.stories.tsx
  src/components/charts/bar-chart/SingleCategoryHorizontalBarChart.tsx
  src/components/charts/bar-chart/SingleCategoryVerticalBarChart.stories.tsx
  src/components/charts/bar-chart/SingleCategoryVerticalBarChart.tsx
  src/components/common/Atoms/badge/IndicateBadge.stories.tsx
  src/components/common/Atoms/badge/IndicateBadge.tsx
  src/components/common/Atoms/badge/RoomBadge.stories.tsx
  src/components/common/Atoms/badge/RoomBadge.tsx
  src/components/common/Atoms/badge/ScoreBadge.stories.tsx
  src/components/common/Atoms/badge/ScoreBadge.tsx
  src/components/common/Atoms/buttons/NotiBellButton.tsx
  src/components/common/Monocles/chart-label/CommonChartLabel.stories.tsx
  src/components/common/Monocles/chart-label/CommonChartLabel.tsx
  src/components/icon/index.tsx
  src/components/ui/badge.tsx
  tailwind.config.ts
Labels: 🎨 스타일

#27 style: tailwind config 추가함.
  tailwind.config.ts
Labels: 🎨 스타일, 🏗️ 환경설정, 📝 문서

#29 add: 대시보드 area 차트 추가
  src/app/page.tsx
  src/asset/Icons/ic-tooltip.svg
  src/asset/Icons/index.tsx
  src/components/charts/CustomLables.tsx
  src/components/charts/GradientChart.stories.tsx
  src/components/charts/GradientChart.tsx
  src/components/charts/GradientTooltip.tsx
  src/components/charts/MainVerticalBarChart.tsx
Labels: 🎨 스타일

#31 add: selectbox 스타일 및 기본 기능 구현
  package-lock.json
  package.json
  src/asset/Icons/account.svg
  src/asset/Icons/building.svg
  src/asset/Icons/index.tsx
  src/components/common/Atoms/avatar/AvatarProfile.stories.tsx
  src/components/common/Atoms/avatar/AvatarProfile.tsx
  src/components/common/Atoms/avatar/BuildingRoomAvatar.stories.tsx
  src/components/common/Atoms/avatar/BuildingRoomAvatar.tsx
  src/components/common/Atoms/seletbox/BuildingSelectbox.stories.tsx
  src/components/common/Atoms/seletbox/BuildingSelectbox.tsx
  src/components/common/Atoms/seletbox/CustomSelect.tsx
  src/components/common/Atoms/seletbox/QuarterSelectbox.stories.tsx
  src/components/common/Atoms/seletbox/QuarterSelectbox.tsx
  src/components/ui/avatar.tsx
  src/components/ui/select.tsx
  src/constants/index.ts
  src/lib/sortedLists.ts
  src/types/common/selectbox.ts
Labels: ✨ 기능구현, 🎨 스타일

#35 Refactor: circle progress bar npm 커스텀 라이브러리로 대체
  package-lock.json
  package.json
  src/components/charts/bar-chart/SingleCategoryVerticalBarChart.tsx
  src/components/common/Atoms/progress-bar/CircleProgressBar.tsx
  src/components/common/Atoms/progress-bar/HalfCircleProgressBar.tsx
  src/lib/@alptugidin/react-circular-progress-bar/README.md
  src/lib/@alptugidin/react-circular-progress-bar/index.d.ts
  src/lib/@alptugidin/react-circular-progress-bar/index.esm.js
  src/lib/@alptugidin/react-circular-progress-bar/index.js
  src/lib/@alptugidin/react-circular-progress-bar/package.json
Labels: 🐛 버그, ♻️ 리팩토링

#37 Feat: msw 환경설정
  .env.development
  .env.production
  .vscode/tasks.json
  src/app/api/mock/exam/route.ts
  src/app/api/mock/route.ts
  src/app/layout.tsx
  src/mocks/MswProvider.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/http.ts
  src/services/api.ts
  start.ps1
Labels: ✨ 기능구현, 🏗️ 환경설정

#39 feat: 계약기간, 슬래시 progressbar 추가
  package-lock.json
  package.json
  src/app/globals.scss
  src/asset/Icons/dash-line.svg
  src/asset/Icons/index.tsx
  src/components/common/Monocles/progress-bar/ContractProgress.stories.tsx
  src/components/common/Monocles/progress-bar/ContractProgress.tsx
  src/components/ui/progress.stories.tsx
Labels: ✨ 기능구현, 🎨 스타일

#43 style: pie chart 커스텀
  src/components/charts/pie-chart/ScorePieChart.stories.tsx
  src/components/charts/pie-chart/ScorePieChart.tsx
Labels: 🎨 스타일

#60 refactor: selectbox 범용성 확장
  package-lock.json
  src/app/(after-login)/dashboard/@MainEver/_components/SelectComp.tsx
  src/asset/Icons/icon_building.svg
  src/asset/Icons/icon_calendar.svg
  src/asset/Icons/icon_room.svg
  src/asset/Icons/index.tsx
  src/components/common/Atoms/seletbox/BuildingSelectbox.stories.tsx
  src/components/common/Atoms/seletbox/CustomSelect.tsx
  src/components/common/Atoms/seletbox/QuarterSelectbox.stories.tsx
  src/components/common/Atoms/seletbox/QuarterSelectbox.tsx
  src/components/common/Atoms/seletbox/Selectbox.stories.tsx
  src/components/common/Atoms/seletbox/Selectbox.tsx
  src/lib/sortedLists.ts
  src/types/common/selectbox.ts
Labels: ♻️ 리팩토링, 🎨 스타일

#62 feat: 호실 페이지 초기 설정
  src/app/(after-login)/room/@CategoryRating/page.tsx
  src/app/(after-login)/room/@Overview/page.tsx
  src/app/(after-login)/room/@RatingManagement/page.tsx
  src/app/(after-login)/room/@RatingTrend/page.tsx
  src/app/(after-login)/room/default.tsx
  src/app/(after-login)/room/layout.tsx
Labels: ✨ 기능구현, 🏗️ 환경설정

#70 fix: 패키지 재설치
  package-lock.json
  package.json
  public/mockServiceWorker.js
Labels: 🐛 버그

#71 feat: [공통] switch 컴포넌트 구현
  package-lock.json
  package.json
  src/asset/Icons/index.tsx
  src/components/charts/pie-chart/ScorePieChart.stories.tsx
  src/components/common/Atoms/seletbox/Selectbox.stories.tsx
  src/components/common/Atoms/switch/ToggleSwitch.stories.tsx
  src/components/common/Atoms/switch/ToggleSwitch.tsx
  src/components/ui/switch.tsx
Labels: 🎨 스타일

#68 feat: 계약 정보 섹션 구현
  src/app/(after-login)/room/@Overview/_component/ContractInfoClientComp.tsx
  src/app/(after-login)/room/@Overview/_component/ContractInfoServerComp.tsx
  src/app/(after-login)/room/@Overview/_component/ContractRentInfo.tsx
  src/app/(after-login)/room/@Overview/page.tsx
  src/components/common/Monocles/progress-bar/ContractProgress.stories.tsx
  src/components/common/Monocles/progress-bar/ContractProgress.tsx
  src/utils/index.ts
Labels: ✨ 기능구현

#74 feat: 내호실 평가 관리 섹션 구현
  src/app/(after-login)/room/@RatingManagement/_component/RatingManagementClientComp.tsx
  src/app/(after-login)/room/@RatingManagement/_component/RatingManagementServerComp.tsx
  src/app/(after-login)/room/@RatingManagement/page.tsx
  src/app/(after-login)/room/layout.tsx
  src/components/common/Monocles/progress-bar/ReviewTrackProgress.tsx
Labels: ✨ 기능구현

#77 feat: 히스토그램 바차트 구현
  next.config.mjs
  package-lock.json
  package.json
  src/components/charts/CustomTooltip.tsx
  src/components/charts/bar-chart/ScoreTrendChart.stories.tsx
  src/components/charts/bar-chart/ScoreTrendChart.tsx
  src/components/charts/line-chart/ScoreTrendChart.tsx
Labels: ✨ 기능구현

#79 fix: esbuild 에러 수정
  package-lock.json
  package.json
Labels: 🐛 버그

#81 fix: cn twMerge 버그 수정
  src/lib/utils.ts
Labels: 🐛 버그

#84 style: 입주 평가하기 - 홈 / 내 호실 평가하기 메인 퍼블리싱
  package-lock.json
  src/app/(after-login)/user-survey/[...surveyStep]/page.tsx
  src/app/(after-login)/user-survey/_components/RoomSurveyMain.tsx
  src/app/(after-login)/user-survey/_components/SurveyHeader.tsx
  src/app/(after-login)/user-survey/_components/SurveyHeaderBackButton.tsx
  src/app/(after-login)/user-survey/default.tsx
  src/app/(after-login)/user-survey/layout.tsx
  src/app/(after-login)/user-survey/page.tsx
  src/asset/Icons/icon_arrow_left.svg
  src/asset/Icons/icon_survey.svg
  src/asset/Icons/icon_survey_btn1.svg
  src/asset/Icons/icon_survey_btn2.svg
  src/asset/Icons/icon_survey_btn3.svg
  src/asset/Icons/index.tsx
  src/asset/Icons/survey_room.svg
  src/asset/images/surveyGnb.png
  src/asset/images/surveyView.png
  src/constants/index.ts
Labels: 🎨 스타일

#73 feat: 호실 평가 상세 페이지 구현
  package-lock.json
  package.json
  src/app/(after-login)/rating-detail/_component/BookmarkButtons.tsx
  src/app/(after-login)/rating-detail/_component/RatingDeatilSearchInput.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailDataTable.tsx
  src/app/(after-login)/rating-detail/_component/RatingDetailFilter.tsx
  src/app/(after-login)/rating-detail/_store/index.ts
  src/app/(after-login)/rating-detail/_store/ratingDetailStore.ts
  src/app/(after-login)/rating-detail/default.tsx
  src/app/(after-login)/rating-detail/layout.tsx
  src/app/(after-login)/rating-detail/page.tsx
  src/asset/Icons/ic-x.svg
  src/asset/Icons/icon_bookmark.svg
  src/asset/Icons/icon_filter.svg
  src/asset/Icons/icon_search.svg
  src/asset/Icons/icon_total.svg
  src/asset/Icons/index.tsx
  src/components/common/Atoms/buttons/IconButtons.tsx
  src/components/common/Atoms/buttons/SwitchButton.stories.tsx
  src/components/common/Atoms/buttons/SwitchButton.tsx
  src/components/common/Atoms/input/SearchInput.stories.tsx
  src/components/common/Atoms/input/SearchInput.tsx
  src/components/common/Monocles/popover-trigger/Popover.stories.tsx
  src/components/common/Monocles/popover-trigger/PopoverContent.tsx
  src/components/common/Monocles/popover-trigger/PopoverTrigger.tsx
  src/components/common/Organisms/navigation/DesktopGNB.tsx
  src/components/ui/button.stories.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  src/components/ui/table.tsx
  src/lib/utils.ts
Labels: ✨ 기능구현
